### ISSUE TITLE
ch5 add tests and solutions

### ISSUE THREAD

**Issue by oldfartdeveloper** [purescript-contrib/purescript-book#108]
Per issue #79

@p2327 and @oldfartdeveloper are discussing **[here](https://github.com/purescript-contrib/purescript-book/issues/79#issuecomment-619330925)** and **[here](https://github.com/purescript-contrib/purescript-book/issues/79#issuecomment-619360788)**.

**Comment by oldfartdeveloper** [comment]
@p2327 - I've signed up for adding tests/solutions to chapter 7 (#109).  You are welcome to this issue if you want it.

**Comment by dvail** [comment]
Is anyone currently working this? I'm studying through chapter 5 myself right now, and can open a PR with my solutions once I'm finished.

**Comment by milesfrain** [comment]
@dvail That would be great. Thanks for checking. I'll assign this task to you so we don't have multiple people working on it simultaneously.
