### ISSUE TITLE
Ch4 excercises FileOperations module missing

### ISSUE THREAD

**Issue by mjarosie** [purescript-contrib/purescript-book#133]
"[A Virtual Filesystem](https://book.purescript.org/chapter4.html#a-virtual-filesystem)" part of Chapter 4 mentions (and uses further in `PSCi` session) a `FileOperations` module. `FileOperations` is not present in [excercises/chapter4](https://github.com/purescript-contrib/purescript-book/tree/master/exercises/chapter4) directory at the moment. Would that make sense to "pre-populate" this file with an empty module asking the user to implement methods mentioned in the content of the book?

**Comment by milesfrain** [comment]
Good catch! The contents of the `FileOperations` module were moved to `Test.Solutions` module in #106 . I'll update the text accordingly.
BTW, we're in the middle of adding tests and instructions to each of the chapters. Ch4 should be complete. Some notes on running the tests as you work through the exercises is described in #79

**Comment by milesfrain** [comment]
Fixed in #134
