### ISSUE TITLE
Importing logShow

### ISSUE THREAD

**Issue by Mateiadrielrafael** [purescript-contrib/purescript-book#136]
So a friend of mine started reading trough the book, and when he got to [the getting-started section](https://book.purescript.org/chapter2.html) - which told him to use the logShow function - he was really confused because he got an error (caused by the fact logShow wasn't imported).

So that section already explains importing Math and Prelude so I think we should add another note on importing the logShow function.

**Comment by milesfrain** [comment]
In the [previous section](https://book.purescript.org/chapter2.html#hello-purescript), it instructs users to start with this:
```hs
module Main where

import Effect.Console

main = log "Hello, World!"
```
But I agree that this is not the most straightforward presentation. I'd like to overhaul this chapter as described in #93.

**Comment by milesfrain** [comment]
#144 should improve this getting-started experience.
