### ISSUE TITLE
Where do I get answers to in-chapter exercises

### ISSUE THREAD

**Issue by venil7** [purescript-contrib/purescript-book#141]
Chapter 4 has exercises:
https://github.com/purescript-contrib/purescript-book/blob/master/text/chapter4.md#exercises-3

where do i get answers for those and others?

**Comment by milesfrain** [comment]
The [solutions](https://github.com/purescript-contrib/purescript-book/tree/solutions) branch.

I'll keep this issue open until a link to the solutions is added to the book.

**Comment by milesfrain** [comment]
Also, we have a linkable mdbook available too, not sure whether that's nicer to read than the github .md viewer.
https://book.purescript.org/chapter4.html#exercises-3

**Comment by venil7** [comment]
sorry, im not finding solutions for chapter7 for example in `solutions` branch

why does it have ti be on a separate branch?

it would be much simpler if solutions where in the end of every chapter so readers can quickly check themselves

**Comment by milesfrain** [comment]
The solutions-as-branch strategy is to make it easier to eventually enable CI that verifies that everything still works with the latest compiler version and package sets.

Ch7 exercises were just added two days ago, but there are some revisions I'd like to make to the solutions before those go in too. I'll update this thread when those go in. Should be in the next day or so.

Here are solutions to some of the exercises, although there are some improvements that need to me made.
https://github.com/oldfartdeveloper/purescript-book/blob/3185c7f6abd68f62525a836f6ff69f863a08b876/exercises/chapter7/test/Solutions.purs

**Comment by milesfrain** [comment]
@venil7 
Revised Ch7 exercises and tests are now available. I believe these are a lot clearer, so I'd recommend grabbing the latest version.
The accompanying solutions are also now uploaded.

**Comment by milesfrain** [comment]
Filed #154 with a proposal to move away from solutions branch.
Let me know if the proposed reader workflow looks reasonable.
