### ISSUE TITLE
Track solutions in master

### ISSUE THREAD

**Issue by milesfrain** [purescript-contrib/purescript-book#154]
There are lots of maintenance benefits to tracking solutions in the master branch. I'll make that conversion after #140 and #144 are merged, and if there are no objections.

The plan is to:
* Keep solutions in `test/no-peeking/Solutions.purs`
* Track a blank `test/MySolutions.purs`
* In `test/Main.purs`:
  * Import both `Test.NoPeeking.Solutions` and `Test.MySolutions`
  * Start with all exercises uncommented
    * This will enable easy CI

Then instruct readers to:
1. Delete the `import module Test.NoPeeking.Solutions` line
1. Block-comment all tests
1. Add their solutions to `Test.MySolutions.purs`
1. Uncomment tests as they solve each exercise

This new process makes things a bit more annoying for readers by adding steps 1 and 2.

cc @oldfartdeveloper

**Comment by milesfrain** [comment]
If we're planning a processing step in CI to strip out anchor comments in #90, we could also automate steps 1 and 2 above so the reader doesn't have to do these manually.

**Comment by oldfartdeveloper** [comment]
@milesfrain Just caught this: the solutions should be kept in `test/no-peeking/Solutions.purs`, not `test/no-peaking/Solutions.purs`.

**Comment by oldfartdeveloper** [comment]
@milesfrain In instruction 1 above, change code to `import Official.Solutions` instead of `import module OfficialSolutions`.

**Comment by milesfrain** [comment]
> In instruction 1 above, change code to `import Official.Solutions` instead of `import module OfficialSolutions`.

Went with `Test.NoPeeking.Solutions` in #168 and edited original post.
