### ISSUE TITLE
Add note about Promise flattening?

### ISSUE THREAD

**Issue by milesfrain** [purescript-contrib/purescript-book#167]
Promises are featured in the FFI chapter and somewhat in the Aff chapter.

There's a potential issue with flattening described in https://github.com/Thimoteus/purescript-promises/issues/12

Should a similar note be included in this book?

Additional discussion in https://github.com/purescript-contrib/purescript-book/pull/140#discussion_r426186259 and https://github.com/purescript-contrib/purescript-book/pull/163#discussion_r439101512

**Comment by hdgarrood** [comment]
I think we could do with a note somewhere which addresses the question of why Aff exists and we don't just use Promise, but I'm not sure if the book is the right place for it. To me it feels like something we can let people seek answers for themselves if they care, and if they don't care it would be better to let them focus on learning PureScript. Perhaps the Aff repo would be a good place for it?

**Comment by JordanMartinez** [comment]
> To me it feels like something we can let people seek answers for themselves if they care, and if they don't care it would be better to let them focus on learning PureScript. Perhaps the Aff repo would be a good place for it?

I like that approach. The `Aff` repo sounds sensible to me.
