### ISSUE TITLE
Chapter 3 example removeDuplicates unused first two arguments

### ISSUE THREAD

**Issue by myrddin89** [purescript-contrib/purescript-book#178]
Hi, I just started learning PureScript reading this book, so this may be something I do not understand.

I cloned the repo on master as suggested in the book to experiment with the exercises.

The example for `removeDuplicates` is defined with `firsName` and `lastName` arguments, but it does not use them in the definition, so to my understanding this should be fixed. Also, I think it should be clarified if one wants to remove _all_ the duplicates or only those matching a particular entry as the solution would suggest. 

Thanks for helping.

**Comment by milesfrain** [comment]
Great catch!
Would you be up for making a PR with the fix?

**Comment by myrddin89** [comment]
Yes, of course!

**Comment by dvail** [comment]
Just ran into this myself, checked this repo and saw the fix was merged 3 hours ago. Awesome!
