### ISSUE TITLE
Ch8 potential mixup of Apply and Applicative

### ISSUE THREAD

**Issue by ursi** [purescript-contrib/purescript-book#184]
https://book.purescript.org/chapter8.html#monads-and-applicatives

It says
> there is also an implementation of the `Applicative` type class which comes "for free" for any instance of `Monad`

and then proceeds to define an `apply`-like function called `ap`. But `apply` is defined for the `Apply` type class. The `Applicative` type class just introduces `pure`. Would this make more sense if `Applicative` was replaced with `Apply`?

**Comment by milesfrain** [comment]
I agree that this looks like a typo. Thanks for the close reading and catching this.
I'd approve a PR with the fix.
