### ISSUE TITLE
usage of "sed" in resetSolutions.sh leads to error on macOS

### ISSUE THREAD

**Issue by Ding-Fan** [purescript-contrib/purescript-book#194]
I followed [text/chapter2.md](https://github.com/purescript-contrib/purescript-book/blob/master/text/chapter2.md) trying to reset the exercise solutions. Then error occurred:

```
sed: 1: "exercises/chapter10/tes ...": invalid command code e
sed: 1: "exercises/chapter11/tes ...": invalid command code e
sed: 1: "exercises/chapter12/tes ...": invalid command code e
sed: 1: "exercises/chapter13/tes ...": invalid command code e
sed: 1: "exercises/chapter14/tes ...": invalid command code e
sed: 1: "exercises/chapter2/test ...": invalid command code e
sed: 1: "exercises/chapter3/test ...": invalid command code e
sed: 1: "exercises/chapter4/test ...": invalid command code e
sed: 1: "exercises/chapter5/test ...": invalid command code e
sed: 1: "exercises/chapter6/test ...": invalid command code e
sed: 1: "exercises/chapter7/test ...": invalid command code e
sed: 1: "exercises/chapter8/test ...": invalid command code e
sed: 1: "exercises/chapter9/test ...": invalid command code e
```

According to [this article](https://ed.gs/2016/01/26/os-x-sed-invalid-command-code/) , I should edit [this line](https://github.com/purescript-contrib/purescript-book/blob/4625828f75cc83823f64ef6b5f7d72839b0127fc/scripts/resetSolutions.sh#L10) as below:

```diff
- sed -i '/Note to reader: Delete this line/d' $d/test/Main.purs
+ sed -i "" '/Note to reader: Delete this line/d' $d/test/Main.purs
```

Maybe we could use some tricks like [this](https://stackoverflow.com/a/51060063/6236633) to make it compatible with different system.

**Comment by milesfrain** [comment]
Sure. Either the solution you linked or the `perl` one look good.

Would you be up for making a PR that you confirm works on macOS, and then I'll test on linux and merge?

**Comment by Ding-Fan** [comment]
It's my first time to use `perl` , please review carefully 😬
I found some usage reference links and put them in the commit message.

**Comment by milesfrain** [comment]
Excellent. Thanks for the help with this.
