### ISSUE TITLE
Minor Clarification: Data Constructors vs Type Constructors

### ISSUE THREAD

**Issue by RAbraham** [purescript-contrib/purescript-book#203]
Hi,
Very minor, but I was wondering about the following text in [Chapter 5](https://github.com/purescript-contrib/purescript-book/blob/master/text/chapter5.md#record-patterns-and-row-polymorphism):
```
The type's constructors are defined after the equals symbol, and are separated by pipe characters (|).
```
Should it be 

```
The type's *data* constructors are defined after the equals symbol, and are separated by pipe characters (|).
```

.. as `type's constructor` could also mean it's `type constructor` which to my newbie knowledge is on the left of the equals symbol?

**Comment by milesfrain** [comment]
Your proposal may be more precise. If so, there's another place to enhance clarity:
https://github.com/purescript/documentation/blob/master/language/Types.md#tagged-unions
> Foo is a tagged union type which has two constructors. Its first constructor Foo takes no arguments, and its second Bar takes one

**Comment by hdgarrood** [comment]
“Constructor” on its own means the same thing as “data constructor”. It never means “type constructor” - you have to include the “type” prefix if that’s what you want to say.

**Comment by emiel** [comment]
I initially struggled with this as well. You could consider including @hdgarrood comment in the text to make the reader of aware of this convention, i.e., make it explicit.

**Comment by RAbraham** [comment]
Thanks @milesfrain and @hdgarrood. If that's the case, then I second @emiel 's suggestion. If you guys agree, I can push a PR.

**Comment by milesfrain** [comment]
> I can push a PR

I'm always happy to see additional clarifications in the text.

**Comment by RAbraham** [comment]
[PR](https://github.com/purescript-contrib/purescript-book/pull/205) submitted
