### ISSUE TITLE
Ch4 whereIs signature does not match instructions

### ISSUE THREAD

**Issue by ericArbour** [purescript-contrib/purescript-book#222]
Hi there, I found another small inconsistency in chapter 4, this time with the `whereIs` exercise.

The instructions state the "function should return a value of type `Maybe Path`." However, the test/solution use `Maybe String`.  

I'm happy to submit a fix to either update the instructions or the test/solution, whichever is preferred. Thanks!

**Comment by milesfrain** [comment]
Yep. Good catch.
Let's go with fixing the solution so it returns `Maybe Path`. I'll merge your PR when it's available.

Also, please share links to the problematic sections to make these issues easier to investigate. For example:
https://book.purescript.org/chapter4.html#exercises-4
https://github.com/purescript-contrib/purescript-book/blob/259fa0db61e6d11d9b30227bbdbf24f42f04c94b/exercises/chapter4/test/no-peeking/Solutions.purs#L130-L131
https://github.com/purescript-contrib/purescript-book/blob/259fa0db61e6d11d9b30227bbdbf24f42f04c94b/exercises/chapter4/test/Main.purs#L162-L165

**Comment by ericArbour** [comment]
Here's a PR for the fix: #224. I'll make sure to link relevant code going forward. Thanks!
