### ISSUE TITLE
Ch6 - Clarify hashes 2nd exercise

### ISSUE THREAD

**Issue by razcore-art** [purescript-contrib/purescript-book#229]
Exercise is:

> 2. (Medium) Write a function arrayHasDuplicates which tests if an array has any duplicate elements. **Use hash-equality from the hashEqual function as an approximation to value equality**. Remember to check for value equality using == if a duplicate pair is found. Hint: the nubByEq function in Data.Array should make this task much simpler.

The highlighted portion is misleading. I had to check the solutions to see what's going on and surely it includes equality for values as well as the hashes. This isn't what the exercise asks. I think it should include value equality as well just to make it more interesting otherwise the solution would be too simple: `arrayHasDuplicates = nubByEq hashEqual`.

**Comment by milesfrain** [comment]
Yep. I remember having to re-read this exercise a bunch of times myself.
Feel free to make a PR with the improvements you have in-mind.
