### ISSUE TITLE
Ch7 - Clarify applicative validation

### ISSUE THREAD

**Issue by razcore-art** [purescript-contrib/purescript-book#231]
# Issue 1

`nonEmpty` is defined and used in `validatePerson` like so:

```purs
nonEmpty :: String -> Either String Unit
nonEmpty "" = Left "Field cannot be empty"
nonEmpty _  = Right unit

validatePerson :: Person -> Either String Person
validatePerson p =
  person <$> (nonEmpty p.firstName *> pure p.firstName)
         <*> (nonEmpty p.lastName  *> pure p.lastName)
         <*> pure p.address
         <*> pure p.phones
```

One wonders why `nonEmpty` isn't defined instead as:

```purs
nonEmpty :: String -> Either String String
nonEmpty "" = Left "Field cannot be empty"
nonEmpty s  = Right s

validatePerson :: Person -> Either String Person
validatePerson p =
  person <$> nonEmpty p.firstName
         <*> nonEmpty p.lastName
         <*> pure p.address
         <*> pure p.phones
```

# Issue 2

Here we're also introduced for the first time to `(*>)` operator which in my opinion is explained very poorly. Since `(<*>)` was already explained in the previous section as an alias for `apply` I think `(*>)` is much better presented as in the docs, where we're told that (*>) keeps the results of the second computation, and throws away the results of the first. Maybe the signature should be given too.

# Issue 3

The code uses the field `homeAddress` instead of `address`.

**Comment by milesfrain** [comment]
Wow. Great find on that first issue. I don't see a reason to mention `*>` at all in this chapter, so I would be in favor of stripping that out of the code. Let's **wait a day for feedback** on this proposal before making the PR.

Note that this validation code is reused in a few upcoming chapters, and it would be best to tackle all of these chapters in a single PR.

It seems like the book is trying to come up with some motivating examples for `*>`, but these aren't a great fit. I think better examples can be found in [routing](https://github.com/purescript-contrib/purescript-routing/blob/main/GUIDE.md). I'd also like to add some concrete example to the [pursuit docs](https://pursuit.purescript.org/packages/purescript-prelude/4.1.1/docs/Control.Apply#v:applyFirst).

With so much code to change that's also duplicated as snippets, this seems like a good candidate for anchored snippets (https://github.com/purescript-contrib/purescript-book/issues/90). I'll make a PR for that in this chapter. That should fix the `homeAddress`/`address` inconsistency too.

**Comment by milesfrain** [comment]
> With so much code to change that's also duplicated as snippets, this seems like a good candidate for anchored snippets (#90). I'll make a PR for that in this chapter. That should fix the `homeAddress`/`address` inconsistency too.

#239 is the PR. Once that's merged, we can add anchors to the other chapters with this `AddressBook` code, then finally remove those unnecessary `*>`s.

**Comment by milesfrain** [comment]
#239 is merged, so now we're ready to remove `*>` from the validation code in Chapters 7,8,10.

@razcore-art, would you like to make the PR for this issue?

**Comment by razcore-art** [comment]
I'm a bit busy these days, but if you're not in a hurry I can take a look *slowly* :)

**Comment by razcore-art** [comment]
@milesfrain so I've looked a bit at this and there's also the [Traversable Tunctors](http://localhost:3000/chapter7.html#traversable-functors) sub-chapter that depends on `arrayNonEmpty` to be:

```purs
arrayNonEmpty :: forall a. String -> Array a -> V Errors Unit
```
instead of

```purs
arrayNonEmpty :: forall a. String -> Array a -> V Errors (Array a)
```
so it's an excuse to showcase `traverse`:

```purs
validatePerson :: Person -> V Errors Person
validatePerson p =
  person <$> (nonEmpty "First Name" p.firstName *> pure p.firstName)
         <*> (nonEmpty "Last Name"  p.lastName  *> pure p.lastName)
         <*> validateAddress p.address
         <*> (arrayNonEmpty "Phone Numbers" p.phones *>
              traverse validatePhoneNumber p.phones)
```

---

What do you want to do about this sub-chatper?

**Comment by milesfrain** [comment]
That's another good point. I suspect there's a cleaner way to write the following where we don't need to duplicate `p.phones` and could avoid `*>`, but I haven't figured this out yet (#243 is the farthest I've got).
```purs
(arrayNonEmpty "Phone Numbers" p.phones *>
 traverse validatePhoneNumber p.phones)
```
Have you found a better solution?

If we must keep `*>` for this last example, that's okay. We'd just want to shift the note about `*>` farther down. Also interesting that it doesn't matter whether we use `*>` or `<*` here.

**Comment by razcore-art** [comment]
Weeeelll I do have solutions, but it will change the functions... functionality. For example instead of `arrayNonEmpty` we'd have a function like so:

```purs
validatePhoneNumbers :: String -> Array PhoneNumber -> V Errors (Array PhoneNumber)
validatePhoneNumbers field [] =
  invalid [ "Field '" <> field <> "' must contain at least one value" ]
validatePhoneNumbers _     phones  =
  traverse validatePhoneNumber phones
```

So it's not just validating that the array is not empty but also that the phones are formatted correctly.

**Comment by milesfrain** [comment]
`validatePhoneNumbers` looks good to me.
