### ISSUE TITLE
Rethink Chapter 8

### ISSUE THREAD

**Issue by dwhitney** [purescript-contrib/purescript-book#25]
Chapter 8 required a complete rewrite once 0.12 was released because `Effect` replaced the old `Eff` Monad. I am personally not very satisfied with my rewrite. It's a tough chapter, and should probably be simplified. Thoughts and suggestions are welcome!

**Comment by milesfrain** [comment]
I'm wondering why the [original address book example](https://github.com/paf31/purescript-book/blob/master/exercises/chapter8/src/Main.purs) was converted to the [reddit example](https://github.com/dwhitney/purescript-book/blob/master/exercises/chapter8/src/Main.purs)? ([commit](https://github.com/dwhitney/purescript-book/commit/a529d155bf272086b213fc7cc43dbd8cb37c030b#diff-91256db4bf5c5311d7ff2f1e77f21a15
) for reference)

Should we add another exercise section that makes use of the reddit example? What about restoring and updating the address book example so the original exercises are more applicable?

I'm happy to attempt to help with this ch8 rewrite, although I'm unlikely to be the best documentation authority as I'm still trying to get a better understanding of how everything works pre and post 0.12.

Also, I see that these sections of [paf31 ch8](https://github.com/paf31/purescript-book/blob/master/text/chapter8.md):
```
Extensible Effects
Interleaving Effects
The Kind of Eff
Records And Rows
Fine-Grained Effects
Handlers and Actions
Mutable State
Exercises
DOM Effects
An Address Book User Interface
Exercises
Conclusion
```
were replaced by these sections in [dwhitney ch8](https://github.com/dwhitney/purescript-book/blob/master/text/chapter8.md):
```
The Aff Monad
Effect to Aff and Aff to Effect
launchAff_ vs launchAff
MonadError
```

Is there opportunity to update more of the original sections, or have they become irrelevant with the `Eff` to `Effect` transition?

**Comment by dwhitney** [comment]
Hey,

The rational for converting from "Address Book" to "Reddit" is I wanted a
reason to use "Aff", and making API requests seemed like a good reason.
Aside from that there is no other reason.

It'd be great if you rewrote ch8. If you want to go back to Phil's address
book example, that's fine, but I do think that introducing Aff is important
for people coming to PureScript, and I don't think it existed when Phil
originally wrote the book, which is why he didn't cover it. That said, it
could be done in another chapter - totally open to suggestions.

Things to note are the React library used in Phil's example is not as
widely used anymore. People are typically using purescript-react-basic now,
so I'd use that. Also I had a look through the old sections you listed.
"Extensible Effects", "Interleaving Effect", "The Kind of Eff",
"Fine-Grained Effects" are now obsolete (thank god!) and since they are
obsolete, I'm not sure "Records and Rows" really makes sense in this
chapter anymore. It probably would be a good idea to address things like
"Handlers and Actions", "Mutable State" and "DOM Effects", especially if
you want to use purescript-react-basic.

Happy to provide input if you have any questions while rewriting and thanks
for looking at this!

**Comment by milesfrain** [comment]
Found [The Future of the PureScript Book](https://discourse.purescript.org/t/the-future-of-the-purescript-book/969) thread on discourse, and I like your suggestion of covering `Aff` in [ch12](https://github.com/dwhitney/purescript-book/blob/master/text/chapter12.md) `Callback Hell`. The ch12 exercise code covers making [asynchronous HTTP requests](https://github.com/dwhitney/purescript-book/blob/master/text/chapter12.md#a-http-client), which seems like a better place for the Reddit API request example.

I added some more thoughts on updating that chapter in #29 

I appreciate your guidance on the ch8 rewrite, especially with noting which sections can be ignored.

If you or another experienced PS user could share some high-level pointers with any ideas you have for what you'd like to see happen with the remaining chapters, that would help me focus my editing time. Chapters 8-14 are new for me, and there's a high likelihood of me reading too deeply into obsolete sections.

**Comment by milesfrain** [comment]
Code changes in #49.

I'd like to get the code changes looked at before restoring and editing the remaining ch8 sections discussed earlier, since lots of code snippets are referenced in the text.

Some questions:
* Would a `useState` strategy work better than `useReducer`? I suspect that `useState` without actions would be more compact and match the [original code](https://github.com/paf31/purescript-book/blob/master/exercises/chapter8/src/Main.purs) more closely.
* What are thoughts on tooling and project organization:
  * `npm` with `npx` for cached and versioned binaries (including PS compiler version)
  * `parcel` and a compatible IDE for automatic page refresh
  * `index.html` and `index.js` in `src` directory for simplified structure

**Comment by dwhitney** [comment]
Amazing! I will take a look this weekend.

**Comment by milesfrain** [comment]
Closing with merge of #49. Picking-up remainder of these discussion points in #29
