### ISSUE TITLE
Ch5 - Add exercises for newtype

### ISSUE THREAD

**Issue by milesfrain** [purescript-contrib/purescript-book#255]
There's currently a [Newtype section](https://book.purescript.org/chapter5.html#newtypes), but no accompanying exercises.

 Proposing moving this section to before the preceding exercises, and then adding a `newtype` exercise to that cluster.

**Comment by Zelenya** [comment]
This seems to be addressed by https://github.com/purescript-contrib/purescript-book/pull/273
