### ISSUE TITLE
Ch2 Exercises introduces Pursuit with an empty search

### ISSUE THREAD

**Issue by armatures** [purescript-contrib/purescript-book#259]
In the [exercises for chapter 2](https://github.com/purescript-contrib/purescript-book/blob/master/text/chapter2.md#exercises), the user is directed to "search Pursuit to find the module that contains the readFloat function and import that module." The containing module, [`Global`](https://pursuit.purescript.org/packages/purescript-globals/5.0.0/docs/Global#v:readFloat), is deprecated, and Pursuit [no longer indexes deprecated modules](https://github.com/purescript/pursuit/issues/287). The easiest fix would be to change that example to something easy to search for in a package that's not deprecated.

**Comment by milesfrain** [comment]
Thanks for catching and reporting this issue.

Looks like `Global` was deprecated 4 days ago in preparation for our upcoming 0.14 release. 

Unfortunately, Pursuit can become out of sync with what's actually available in latest package set (a bit too bleeding edge in this case). That should improve once we get the new [registry](https://github.com/purescript/registry) online. Until then, you can also check this [pursuit clone](https://spacchetti.github.io/starsuit/#search:readFloat) which is pinned to the latest package set.

Anyway, **let's go with your suggestion of updating the example**.

The replacement for `readFloat` is [`fromString`](https://pursuit.purescript.org/packages/purescript-numbers/7.0.0/docs/Data.Number#v:fromString), but that's not very beginner-friendly to search for and `Maybe` is another unfamiliar concept.

I can't think of anything else that's chapter-2-appropriate to search for on pursuit. Let me know if you have any ideas. We can alternatively defer the pursuit exercise until a later chapter.

**Comment by armatures** [comment]
I'm not sure how the Global package was brought in, but it's nice to have a function to look up that's already a dependency, so the user doesn't have to learn about adding them. Maybe Global is special somehow in that regard? Grepping global doesn't really bring anything up for me in the project—it's not important except that it would be nice to replace the exercise with something that had that same property. `Math` is already in scope, so maybe the Pursuit search could be for `remainder` or something? All the other function names in that package are abbreviated and so not particularly searchable.

It might be silly, but we could do something like `isDivisibleBy3`. Maybe this problem stumbles into `Number` vs `Int` distinctions, though: running `remainder 9 3` in psci doesn't work, but `remainder 9.0 3.0` is happy.

**Comment by milesfrain** [comment]
I believe `Global` was originally featured in this exercise _because_ it's another module to import.

[`rem`](https://pursuit.purescript.org/packages/purescript-integers/4.0.0/docs/Data.Int#v:rem) from `Data.Int` might be a good substitute.

What about this for an exercise?
> Write a function `leftoverCents` which takes an `Integer` and returns what's leftover after dividing by `100`. Use the `rem` function. Search [Pursuit](https://pursuit.purescript.org/) for this function to learn about usage and which module to import it from. _Note:_ Your IDE may support auto-importing of this function if you accept the auto-completion suggestion.

**Comment by JordanMartinez** [comment]
`Global` will be deprecated in v0.14.0, so you should probably use a different module.

**Comment by gdennie** [comment]
The current simple solution to implementing the last exercise, `leftoverCents`, by searching and importing the remainder function, `rem` function using Pursuit is presently problematic. The simple solution,

```
import Data.Int (rem)
...
leftoverCents d = rem (d / 100.0)
```

...generates the error: `Count not match type Number with type Int`. I presume the exercise was not intended to throw the reader into a Pursuit of experimentation for suitable definitions.

**Comment by milesfrain** [comment]
@gdennie Thanks for the feedback.

Note that `rem` takes _two_ integer arguments (you are just giving it _one_ argument, but also performing an unnecessary division). I was hoping this would be clear with the examples on pursuit, but perhaps they can be improved. I'd be happy to hear any suggestions you have for making this exercise more straightforward for readers.

Here's what I see as my first pursuit [result](https://pursuit.purescript.org/search?q=rem) for `rem`:
```purs
rem :: Int -> Int -> Int

rem 2 3 == 2
```

For context, here's the [exercise](https://book.purescript.org/chapter2.html#exercises):
> (Medium) Write a function `leftoverCents` which takes an `Integer` and returns what's leftover after dividing by `100`. Use the `rem` function. Search Pursuit for this function to learn about usage and which module to import it from. _Note_: Your IDE may support auto-importing of this function if you accept the auto-completion suggestion.

**Comment by gdennie** [comment]
Thanks.

I did realized my mistake in bed reflecting. :)

Incidentally, the exercises should be using `npx`, as in `npx spago test`, to avoid needing global install. It presents a more robust solution especially in docker containers with non root user, which I've setup.

**Comment by milesfrain** [comment]
> Incidentally, the exercises should be using `npx`, as in `npx spago test`, to avoid needing global install. It presents a more robust solution especially in docker containers with non root user, which I've setup.

I think that's more of a matter of preference. For most folks starting out, global install is the most convenient. And if you're installing via `nvm` (as recommended in the "getting started" section), you shouldn't need root access.
