### ISSUE TITLE
readFloat in chapter 2

### ISSUE THREAD

**Issue by nathanielvirgo** [purescript-contrib/purescript-book#262]
Chapter 2 says, in Exercise 2:

> Hint: You should first search Pursuit to find the module that contains the readFloat function and import that module.

There seem to be two issues here.

(1) searching Pursuit for "readFloat" does not return any results

(2) through a bit of Googling I found it in the 'Globals' package - but that package is marked as deprecated

Although I'm a new PureScript user, I'm guessing this means this hint is out of date, and should be replaced with whatever is now the correct way of reading a float.

**Comment by milesfrain** [comment]
Thanks for the report. We're discussing a substitute for `readFloat` in #259. I'll just go ahead with making a PR for the proposal in https://github.com/purescript-contrib/purescript-book/issues/259#issuecomment-749864532

**Comment by milesfrain** [comment]
Fixed by #266
