### ISSUE TITLE
Chapter 2 , Excercise 2 searching for readFloat doesnt work 

### ISSUE THREAD

**Issue by shishini** [purescript-contrib/purescript-book#263]
I just started started learning Purescript
And in chapter 2 Getting Started

The second point in the exercise you are told

    You should first search Pursuit to find the module that contains the readFloat function and import that module.

If you do that, nothing will return, and will look like search don't work
I tried searching for

    readFloat

which returns nothing
and then for

    readFloat()

I added the brackets thinking, maybe search only work on functions if you add brackets
This term return the wrong results

I asked on the purescript channel on freenode and found out that the module Global is deprecated, which was why searching Pursuit didn't work

While I think search on Pursuit should work on even deprecated or obsoleted modules
I think until this happens, if at all it happens we might want to update the book or the example to not use a deprecated module 

But honestly from my side, I think its the search in pursuit that should change

**Comment by milesfrain** [comment]
Sorry about the goose chase with this exercise. This was also reported in #259, and we're planning a correction.

Feel free to suggest any improvements for Pursuit on that tool's issue tracker: https://github.com/purescript/pursuit/issues

**Comment by shishini** [comment]
opened issue [429](https://github.com/purescript/pursuit/issues/429) for Pursuit
