### ISSUE TITLE
Chapter 6 Exercise: Semiring instance for Complex

### ISSUE THREAD

**Issue by shaunplee** [purescript-contrib/purescript-book#277]
I got a little tripped up in trying to use `over2` and `wrap` because I was too dense to understand the error messages regarding the lack of a `Newtype` instance for `Complex`. ("What do you mean there's no `Newtype` instance for `Complex`? It says it right there in the keyword: `newtype Complex`!")

If there are no objections, I will open a PR to indicate that, if the reader chooses to use `over2` and `wrap` as suggested, they will also need to include `class Newtype` in the imports from `Data.Newtype` and add a line to automatically derive a (capital N) `Newtype` instance for `Complex` ala `derive instance newtypeComplex :: Newtype Complex _`.

**Comment by milesfrain** [comment]
That sounds good to me!
