### ISSUE TITLE
Chapter 6: Underscore notation for property accessors used without previously being introduced

### ISSUE THREAD

**Issue by shaunplee** [purescript-contrib/purescript-book#281]
The Functional Dependencies section of Chapter 6 uses underscore notation for an accessor to the `tail` property of a `Stream`:
```
genericTail xs = map _.tail (uncons xs)
```
Grepping the text of the book, this appears to be the only place where this syntax is ever used (there's a match in Chapter 1 with the JavaScript example of `_.chain(_.range(1000))`, but that's not the same thing).

While the syntax is infrequently used in the book, readers may encounter it in other code, and it might be helpful to introduce this syntax when discussing Records in Chapter 3, specifically in after the section on how fields of Records can be accessed using a dot.

An additional suggestion would be to modify `findEntryByStreet` exercise (or add a follow up exercise) to suggest that the predicate supplied to `filter` could be expressed as the composition of an accessor function using the underscore notation and a test for equality, like:
```
(==) street <<< _.address.street
```

**Comment by milesfrain** [comment]
> it might be helpful to introduce this syntax when discussing Records in Chapter 3

That sounds good. We could also link to the reference docs for readers to learn more about how to interact with records. https://github.com/purescript/documentation/blob/master/language/Syntax.md#property-accessors

> modify `findEntryByStreet` exercise (or add a follow up exercise)

This sounds good too.

I notice we also don't cover [operator sections](https://github.com/purescript/documentation/blob/master/language/Syntax.md#operator-sections) shorthand either. I actually thought `_.` for records was just a special case of this technique, but they appear to be separate concepts. This could be a nicer way to introduce `flip`. Wrote a proposal in https://github.com/purescript-contrib/purescript-book/issues/260#issuecomment-753440750
