### ISSUE TITLE
Chapter 6: Exercise - Action m (Self m) - test case tests for situation that was not explicitly asked for

### ISSUE THREAD

**Issue by shaunplee** [purescript-contrib/purescript-book#283]
[Exercise 5](https://book.purescript.org/chapter6.html#exercises-3) to write an instance for `Action m (Self m)` generated a mysterious compiler error when running the tests:
```
  No type class instance was found for
                                           
    Test.MySolutions.Action (Self Multiply)
                            Int   
```
This occurs due to this test:
https://github.com/purescript-contrib/purescript-book/blob/905410c6db1a6d97d58ece06107ba47ffd2aac6b/exercises/chapter6/test/Main.purs#L231-L233

The previous two tests in the suite pass with a simple implementation like:
https://github.com/purescript-contrib/purescript-book/blob/905410c6db1a6d97d58ece06107ba47ffd2aac6b/exercises/chapter6/test/no-peeking/Solutions.purs#L216-L217

This leaves the reader with a mystery as to what the third test is actually testing, as the types of `act (act (m1 <> m2) a) 2` do not match `Action m (Self m)`.

Potential resolutions would be to:
1. delete this particular test
2. add an exercise to ask the reader to also implement the `repeatActionMultiplySelf` instance as shown in the Solutions.purs file.

Any thoughts?

**Comment by milesfrain** [comment]
Great find.

Upon further review of this instance:
https://github.com/purescript-contrib/purescript-book/blob/905410c6db1a6d97d58ece06107ba47ffd2aac6b/exercises/chapter6/test/no-peeking/Solutions.purs#L225-L226
`Action (Self Multiply) Int` doesn't match what the exercise is asking for: `Action m (Self m)`.

So let's remove that test and the accompanying solution code.
See #198 and #199 for context for how that code made it into the book, although I believe it's just #199 that needs to be reverted. It would still be good to find a suitable concrete test replacement. (CC @dvail)

I believe the motivation for the concrete tests was to catch these law-abiding (but incorrect) solutions:
```purs
act _ a = a
```

**Comment by milesfrain** [comment]
Went ahead and created #284 to fix this issue

**Comment by shaunplee** [comment]
I started to hack the original test to fit the `Action m (Self m)` instance like:
```haskell
        test "Multiply Self append concrete" do
          Assert.equal (Self $ Self $ Multiply 72)
            $ act (act (m1 <> m2) a) (Self $ Self $ Multiply 2)
```
but I think your revised tests look nicer.
