### ISSUE TITLE
Handling Regex - best practices

### ISSUE THREAD

**Issue by razcore-art** [purescript-contrib/purescript-book#287]
Ch7, Ch8, Ch10 and maybe some other places use `Data.String.Regex` and it became a bit complicated to handle cases in the test suite and explanations in the book maybe muddy by the use of `Either`. I think this can be a good case to expand on how to handle this cases.

I was just searching for something that involved regex on pursuit and came across [how they use](https://github.com/f-o-a-m/purescript-optparse/blob/v3.0.0/src/Options/Applicative/Internal/Utils.purs#L38) it in `optparse`:

```purs
whitespaceRegex :: Regex
whitespaceRegex = case Regex.regex "\\s+" noFlags of
  Left  err -> unsafeCrashWith $ "whitespaceRegex: `\\s+` seems to be invlaid, err: " <> err
  Right r   -> r
```

So they just get rid of `Either` off the bat which makes perfect sense cause regex in this case is composed of a `String` literal we come up with so it's hard coded. Only case this fails is if we make a mistake or if there's something wrong with our system/javascript engine.

So maybe we should use something similar and explain a bit about best practices and how not to complicate stuff down the line unnecessarily.

**Comment by ptrfrncsmrph** [comment]
I would also think that using `unsafeRegex` when constructing a static regex is relatively "safe". See also: https://twitter.com/jbrains/status/1339318230670774273?s=20

**Comment by razcore-art** [comment]
I wasn't aware of that function, thanks :)

**Comment by milesfrain** [comment]
Is this a proposal to revert #248 in favor of the [`unsafeRegex`](https://pursuit.purescript.org/packages/purescript-strings/4.0.1/docs/Data.String.Regex.Unsafe#v:unsafeRegex) helper function? Or to merely add some additional explanation?

I'd love for there to be a way to perform runtime checks during compilation if the arguments are literal values. But that's a big ask for additional language features.

**Comment by hdgarrood** [comment]
Yes, I think reverting #248 in favour of unsafeRegex makes sense. I don’t think this is asking for additional language features so that you can have regex literals checked at compile time, just a suggestion of using unsafeRegex where the argument is a string literal.

One thing you can do to make unsafeRegex slightly safer to use is to put the regex in its own top level declaration, so that the unsafeRegex call is evaluated immediately upon loading the app; that way you’ll most likely catch it if it does turn out to be invalid.

**Comment by razcore-art** [comment]
> Is this a proposal to revert #248 in favor of the [`unsafeRegex`](https://pursuit.purescript.org/packages/purescript-strings/4.0.1/docs/Data.String.Regex.Unsafe#v:unsafeRegex) helper function? Or to merely add some additional explanation?

Yes, it means we should revert in favor of `unsafeRegex`. I was just getting into contributing to closing issues at the time and I partly agreed that `unsafePartial` isn't what we want there cause:

1. It isn't informative for beginners looking at the code
1. It seemed overly complicated for that particular chapter, I mean students were just barely introduced to type classes one chapter before.

At the time I didn't know about `unsafeRegex` or `unsafeCrashWith` for that matter. I can assign myself to this task cause I'm the one that made the `Either` mess to begin with :)
