### ISSUE TITLE
Ch4 - Is it possible to solve the countEven exercise without pattern matching?

### ISSUE THREAD

**Issue by milesfrain** [purescript-contrib/purescript-book#303]
The solution for the `countEven` [exercise](https://book.purescript.org/chapter4.html#exercises) relies on pattern matching, but that isn't covered until the next chapter. Should we remove that exercise, or reorganize content in the book?

https://github.com/purescript-contrib/purescript-book/blob/4346bb2da05b22fb962beaf101b23e1166566685/exercises/chapter4/test/no-peeking/Solutions.purs#L24-L30

Even if we do want to use pattern matching, this solution can be cleaned-up a bit.

**Comment by hdgarrood** [comment]
I think we can implement countEven without pattern matching by using the same patterns as in the examples just before that exercise. I think we should also avoid making it tail-recursive at least until the reader has reached the section about tail recursion. For example:

```purescript
isEven :: Int -> Boolean
isEven n =
  if n == 0 then
    true
  else if n == 1 then
    false
  else
    isEven (n - (2 * (n / abs n)))

countEven :: Array Int -> Int
countEven arr =
  if null arr
    then 0
    else oneIfEven (fromMaybe 1 $ head arr) + countEven (fromMaybe [] $ tail arr)
  where
  oneIfEven x = if isEven x then 1 else 0
```

However, it does suck to have to do `fromMaybe` on both the head and the tail of the array, and in particular it sucks to have to make up default values in the cases that shouldn't ever happen in practice. I think there is an argument for waiting until after we have introduced pattern matching for these exercises. They'd also be a lot nicer if we used List, I think.

**Comment by milesfrain** [comment]
`isEven` without pattern matching could be cleaned-up a bit to:
```purs
isEven :: Int -> Boolean
isEven n = if n == 0 then
  true
  else not $ isEven $ n - 1
```

But with pattern matching, we can do:
```purs
isEven :: Int -> Boolean
isEven 0 = true
isEven n = not $ isEven $ n - 1
```

Wondering if we should modify the exercise and tests to handle negative inputs.

And for reference, here's the best `countEven` I can think of without a map or fold:
```purs
countEven :: Array Int -> Int
countEven arr = case uncons arr of
  Nothing -> 0
  Just {head: x, tail: xs} -> (if isEven x then 1 else 0) + countEven xs
```
But for these situations, I propose we note that future chapters will show how to rewrite these solutions elegantly, then follow-up. Otherwise, having readers only write the clunky implementations reflects poorly on the language. Here's an example of a nicer `countEven` rewrite:
```purs
countEven :: Array Int -> Int
countEven = length <<< filter isEven
```

Should we even be including these introductory exercises that ask readers to write non-idomatic code? I think we could provide better exercises.

**Comment by hdgarrood** [comment]
I think asking the reader to do at least one or two exercises with explicit recursion is probably good, because you do occasionally see it in the wild even if in most cases you ought to be using maps, filters, folds, and so on. If we ask them to rewrite `countEven` using `filter` once we have covered `filter`, that ought to make up for us asking them to write non-idiomatic code in the first place; that could be a good way to emphasize the point about preferring folds to explicit recursion.

**Comment by hdgarrood** [comment]
I think an implementation which doesn't handle negative inputs is arguably wrong, as the exercise does ask for a function which returns true if and only if its input is an even integer, since negative even integers are still even integers.

**Comment by milesfrain** [comment]
Here's what I'm think for next steps:
* Improve the `isEven` exercise description and tests for handling negative numbers.
* Replace `countEven` with a different recursion exercise.
