### ISSUE TITLE
Chapter 5 - Clipped exercise requires changing many functions

### ISSUE THREAD

**Issue by larskinn** [purescript-contrib/purescript-book#314]
The exercise states:
> Extend the `Shape` type with a new data constructor `Clipped`, which clips another `Picture` to a rectangle. Extend the `shapeBounds` function to compute the bounds of a clipped picture.

But adding the `Clipped` constructor to `Shape` in `Picture.purs` means that, in addition to `shapeBounds`, the following functions need to be extended:
  - `getCenter`
  - `showShape`

Is this intended? It is not mentioned in the exercise text or in the solutions.

Extending `getCenter` and `shapeBounds` was straightforward enough, but I had trouble with `showShape` and just added
```purescript
showShape (Clipped _ _ _) = "Not implemented"
```
so that I could actually run the tests.

**Comment by milesfrain** [comment]
Yep. Those are required extensions. Feel free to add a hint to the exercise text, such as:
> Note: The compiler will walk you through extending other functions as required.
