### ISSUE TITLE
Chapter 8: Tests for fibonacci are off by one fibonacci-number

### ISSUE THREAD

**Issue by larskinn** [purescript-contrib/purescript-book#316]
```
        suite "fibonacci" do
          test "40th Fibonacci number"
            $ Assert.equal 165580141 (fibonacci 40)
          test "45th Fibonacci number"
            $ Assert.equal 1836311903 (fibonacci 45)
```

But unless I'm missing something, it should be this instead:

```
        suite "fibonacci" do
          test "40th Fibonacci number"
            $ Assert.equal 102334155 (fibonacci 40)
          test "45th Fibonacci number"
            $ Assert.equal 1134903170 (fibonacci 45)
```
...at least according to [WolframAlpha](https://www.wolframalpha.com/input/?i=fibonacci%2840%29%2C+fibonacci%2845%29)

If I haven't totally misunderstood something, I can make a PR to correct this.

**Comment by hdgarrood** [comment]
Both definitions are used. See https://github.com/purescript-contrib/purescript-book/issues/315#issuecomment-803626404

This seems to be tripping a few people up though so maybe we should just change it.

**Comment by larskinn** [comment]
I see what you mean.

The [Wikipedia page](https://en.wikipedia.org/wiki/Fibonacci_number) actually mentions three different definitions in the introduction:
  1. `F 0 = 0, F 1 = 1. For n > 1: F n = F (n-1) + F (n-2)`
  2. `F 1 = F 2 = 1. For n > 2: F n = F (n-1) + F (n-2)` -- mentioned in "Some older definitions"
  3. `F 1 = 1, F 2 = 2. For n > 2: F n = F (n-1) + F (n-2)` -- mentioned as the "original definition"

The first definition is what I personally learned in school. For `n >= 1` the first and second definition is equal. [Wolfram MathWorld](https://mathworld.wolfram.com/FibonacciNumber.html) use the second definition, adding that it is customary to set `F 0 = 0`.

The third definition is what's used in this book.

I think it would be better to use definition 1 or 2, as at least all results on the first page of the google searches "fibonacci sequence" and "fibonacci number" use the definition where `F 1 = F 2 = 1`, and not the one where `F 1 = 1, F 2 = 2`.

As an aside, the example `fibonacci` solutions in chapter 4 and 8 are both defined for `n = 0`, but chapter 4 defines it as `1` while chapter 8 defines it as `0`.
