### ISSUE TITLE
Ch. 5. Broken link (Twitter)

### ISSUE THREAD

**Issue by camimora** [purescript-contrib/purescript-book#319]
Hello 👋 , just a small issue:

In chapter 5, section `Newtypes`, the link in the sentence: 
```
This design principle is perhaps better communicated visually.
```
seems to be broken (tweet removed I guess).

The link itself is: https://twitter.com/jusrin00/status/875238742621028355/photo/1

Would be cool to either point to the new location of the image (seems like it was the tweet of an image) or remove the reference.

Cheers!

**Comment by milesfrain** [comment]
Thanks for reporting. Created #320 as one option to fix, but hoping we could get the original twitter link back up, since it's nice to have the discussion on there too.
