### ISSUE TITLE
Chapter 3 - repl print out for "flip" needs updating?

### ISSUE THREAD

**Issue by danielrlc** [purescript-contrib/purescript-book#326]
Should this repl printout in Chapter 3 be updated?

## Book

```
> import Prelude
> :type flip
forall a b c. (a -> b -> c) -> b -> a -> c
```

## repl (for PureScript 0.14.1)

```
> import Prelude
> :type flip
forall (a :: Type) (b :: Type) (c :: Type). (a -> b -> c) -> b -> a -> c
```

In general, would it be better if an edit suggestion like this comes through a PR? (I thought I'd start small, though.)

**Comment by milesfrain** [comment]
Wow. It looks like all `:type` output has been "clarified" with additional _kind_ information (e.g. the _kind_ of a type).
```purs
> :t flip
forall (a :: Type) (b :: Type) (c :: Type). (a -> b -> c) -> b -> a -> c

> :t const
forall (a :: Type) (b :: Type). a -> b -> a

> :t add
forall (a :: Type). Semiring a => a -> a -> a

> :t map
forall (f :: Type -> Type) (a :: Type) (b :: Type). Functor f => (a -> b) -> f a -> f b
```

> In general, would it be better if an edit suggestion like this comes through a PR?

Either a PR or issue is fine. Thanks for reporting.

In this case, I think there's a lot of stuff to sort out, such as:
- Update all repl snippets that print kind info.
- Move everything involving these kind-printing snippets to after the [kind section of ch3](https://book.purescript.org/chapter3.html#type-constructors-and-kinds).
- Move this `flip` example to Ch4 as proposed in https://github.com/purescript-contrib/purescript-book/issues/260#issuecomment-753440750.

Your proposal to include a "Don't worry" note in https://github.com/purescript-contrib/purescript-book/issues/260#issuecomment-828157571 may also be a reasonable temporary fix.

Feel free to make a PR for any of the above todos. You're also welcome to copy over this [series map/flip examples](https://github.com/purescript-contrib/purescript-book/issues/260#issuecomment-753440750) and explanation, if you think that would make sense in Ch4. I'd also be happy to make these edits, but probably won't get around to it within the next month, and want to give first dibs to potential new contributors.

**Comment by danielrlc** [comment]
Thanks for clarifying what was going on in the repl output.

I'll keep working through the book and see what I could make a PR or an issue on, out of the things you suggested.
