### ISSUE TITLE
Use spago?

### ISSUE THREAD

**Issue by FranklinChen** [purescript-contrib/purescript-book#33]
Spago https://github.com/spacchetti/spago seems to have become popular for PureScript projects

**Comment by dwhitney** [comment]
hey sorry I missed this. But I'd like to add an ENTHUSIASTIC YES!

**Comment by FranklinChen** [comment]
Good to see someone working on this at https://github.com/dwhitney/purescript-book/pull/39!

**Comment by emiel** [comment]
Now that https://github.com/purescript-contrib/purescript-book/pull/39 has been merged I suppose this issue may now be closed. Thanks to everyone involved!
