### ISSUE TITLE
Enable gh pages deployment for gh Actions-based workflow

### ISSUE THREAD

**Issue by milesfrain** [purescript-contrib/purescript-book#345]
I was hoping that merging #343 or #344 would deploy the latest version of the book to gh pages, but it's skipping deployment with this error:
> This action runs on a fork and not found auth token, Skip deployment

https://github.com/purescript-contrib/purescript-book/actions/runs/854860824

Here's the relevant code:
https://github.com/purescript-contrib/purescript-book/blob/6dacfa9e98812421f1d33076eff19fc99cf4509f/.github/workflows/mdbook.yml#L21-L27

Thinking it could either be due to an incompatibility of `github.ref == 'refs/heads/master'` with this repo being a fork of `paf31`'s version, or that `GITHUB_REPO_DEPLOY_KEY` is unavailable.

Documentation for this action is available in https://github.com/peaceiris/actions-gh-pages#options

@hdgarrood , we worked through this before in #82. I was hoping that `GITHUB_REPO_DEPLOY_KEY` would still be available for use, but can't inspect the repo's secrets myself to double-check. Could you take a look at this?

**Comment by milesfrain** [comment]
Found some more evidence that this is an issue with an empty `GITHUB_REPO_DEPLOY_KEY` (assigned to `deploy_key`). It should work on forks if `deploy_key` is non-empty.

> This version can skip deployment on forks when `deploy_key` or `personal_token` is empty.

https://github.com/peaceiris/actions-gh-pages/issues/153#issuecomment-599142827

**Comment by hdgarrood** [comment]
There are no secrets configured for this repo right now; I guess I removed the deploy key after we ended up not using it for Travis. I can try adding one again shortly.

**Comment by hdgarrood** [comment]
According to https://github.com/peaceiris/actions-gh-pages, GitHub automatically creates a token called `GITHUB_TOKEN` and this doesn't require any setup. That seems ideal. Could you try doing it that way?

**Comment by milesfrain** [comment]
Fixed by #346
