### ISSUE TITLE
PureScript version installed on your system is not compatible with the package-set you're using

### ISSUE THREAD

**Issue by databrecht** [purescript-contrib/purescript-book#363]
Hey,

did something change recently in purescript that broke the book? It's been a while since I looked at purescript but was going to pick it up again. I installed the latest purescript version (purescript@0.14.2)

```chapter2 ➤ spago test```      

[error] Oh noes! It looks like the PureScript version installed on your system is not compatible with the package-set you're using.

installed `purs` version:    0.13.8
minimum package-set version: 0.14.0

There are a few ways to solve this:
- install a compatible `purs` version (i.e. in the same 'semver range' as the one in the package set)
- if the `purs` version is 'too new', you can try using `spago upgrade-set` to upgrade to the latest package set
- if you know what you're doing and you want to disable this check, you can override the `version` of the `metadata` package in the packages.dhall, e.g.:

  let upstream = <package-set url here>
  in  upstream
    with metadata.version = "v0.13.8"

**Comment by milesfrain** [comment]
We've been keeping the book current with the latest compiler versions (currently 0.14.2).

I suspect that you have an out-of-date clone of the book on your system that points to an older package set. **The best way to solve this is to just update your local copy of the book.** Here's how to do that with git commands:
- Commit all local changes (perhaps create a backup secondary branch before proceeding to the following steps).
- Ensure that `git remote -v` has the upstream `purescript-contrib` repo listed:
   ```
   git remote -v                                                               
   origin  https://github.com/purescript-contrib/purescript-book.git (fetch)
   ```
- Pull the latest changes:
   ```
   git pull --rebase origin master
   ```

If `origin` points to your own forked copy of the book, you can add the `purescript-contrib` remote and then pull from that instead:
```
git remote add upstream https://github.com/purescript-contrib/purescript-book.git
git pull --rebase upstream master
```

If the above steps are too much of a hassle, you could also just re-clone the latest version of the book and copy over any completed answer you want to keep from your current in-progress chapter.

**Comment by databrecht** [comment]
In case other people have this problem and are using nvm. I don't know how it got installed (since this is a new VM) but ```whereis purs``` gave me the answer. Apparently, next to my node_modules under my nvm version, an older binary (13.8) also got installed under /.local/bin/ and it took precedence over the 14.2 version. I must have done something wrong.

Thanks for the help @milesfrain, I'll clone the ticket.
