### ISSUE TITLE
Make comment lines removed by resetSolution.sh less confusing

### ISSUE THREAD

**Issue by milesfrain** [purescript-contrib/purescript-book#370]
Should this line:
```
Note to reader: Delete this line to expand comment block
```
be changed to something like the following for every chapter?:
```
Note to reader: This line should have been automatically deleted by resetSolutions.sh. See Chapter 2 for instructions.
```

**Edit**: Thinking of condensing to just:
```
This line should have been automatically deleted by resetSolutions.sh. See Chapter 2 for instructions.
```

See https://github.com/purescript-contrib/purescript-book/pull/369#discussion_r680304131 for more context

**Comment by ntwilson** [comment]
I think this would make a lot more sense to a new student!  Note this would also mean changing resetSolutions.sh, which currently looks specifically for the text
> Note to reader: Delete this line

Should it just search instead for 
> Note to reader: This line should have been automatically deleted

?
