### ISSUE TITLE
Ch11 switch from yargs to optparse?

### ISSUE THREAD

**Issue by ntwilson** [purescript-contrib/purescript-book#382]
[purescript-yargs](https://github.com/paf31/purescript-yargs) is archived now, and I get the impression that the "standard" alternative these days is [purescript-optparse](https://github.com/f-o-a-m/purescript-optparse).  (There's also [purescript-argparse-basic](https://github.com/natefaubion/purescript-argparse-basic), though I get the impression this isn't established enough for use in educational material).  Should we update chapter 11 to use optparse instead of yargs?  Or is there another library we should use?  I feel like it gives a bad impression if library for CLI args used in the educational materials is no longer maintained. 

Related, if we do switch libraries, is it better to update the package set, or add another override?

**Comment by milesfrain** [comment]
Switching to `optparse` sounds good.

If you're feeling generous, you can add the library to the package set, otherwise an override is fine until the new registry is online.
