### ISSUE TITLE
[Ch3] Indentation docs for `where` are wrong

### ISSUE THREAD

**Issue by keithlayne** [purescript-contrib/purescript-book#397]
In https://book.purescript.org/chapter3.html#notes-on-indentation it says:

> Certain PureScript keywords (such as where, of and let) introduce a new block of code, in which declarations must be further-indented:

and then there's this block:

```hs
example x y z = foo + bar
  where
    foo = x * y
    bar = y * z
```

Unless I'm reading this wrong, it's saying that bindings under `where` must be further indented, which isn't true.

See that chapter's AddressBook.purs, which seems to violate that rule: https://github.com/purescript-contrib/purescript-book/blob/master/exercises/chapter3/src/Data/AddressBook.purs#L62-L69

**Comment by milesfrain** [comment]
Wow. Great catch and attention to detail here!

This note about required `where` indentation was written by the original language creator (see the [same section](https://leanpub.com/purescript/read#leanpub-auto-notes-on-indentation) in the first edition of the book). But the [official reference](https://github.com/purescript/documentation/blob/master/language/Syntax.md#let-and-where-bindings) indicates that `where` blocks don't require indentation.

This is why I wish the book didn't even bother with some of these details, and would instead point to a centralized reference and just focus on exercises. More ranting about that proposal can be found in #340.

Feel free to rewrite part of that section to make it more accurate. Perhaps just replace the `where` example with a `let` example.
