### ISSUE TITLE
chapter 10 double negation intended or typo?

### ISSUE THREAD

**Issue by chriz-zeller** [purescript-contrib/purescript-book#415]
https://github.com/purescript-contrib/purescript-book/blob/6141750d54bfbeddce44b77a9e76c095f69a2179/text/chapter10.md#L1170

It says "cannot not"
- either it is a complicated way to say "can"
- or it is a typo meaning it "can not"

**Comment by mhmdanas** [comment]
It's a typo.

**Comment by Zelenya** [comment]
It was fixed by #424
