### ISSUE TITLE
Chapter 10: Confusion between `id` and `identity` functions

### ISSUE THREAD

**Issue by gemmaro** [purescript-contrib/purescript-book#425]
Hello.
In [Representing Quantified Types](https://book.purescript.org/chapter10.html#representing-quantified-types), it seems that there are confusions between `id` and `identity` functions.

> What sort of functions have this type? Well, there is certainly one function with this type - namely, the `identity` function, defined in the `Prelude`:
>
> ```purescript
> id :: forall a. a -> a
> id a = a
> ```
>
> In fact, the `identity` function ...

Also, I'm sorry if I'm mistaken, but I think neither the `identity` function nor the `id` function are in `Prelude`. `spago repl` is below.

```shell-session
$ spago repl

...

PSCi, version 0.15.4
Type :? for help

import Prelude

> :t id
Error found:
in module $PSCI
at :1:1 - 1:3 (line 1, column 1 - line 1, column 3)

  Unknown value id


See https://github.com/purescript/documentation/blob/master/errors/UnknownName.md for more information,
or to contribute content related to this error.


> :t identity
forall (t27 :: Type) (a :: t27 -> t27 -> Type) (t :: t27). Category @t27 a => a t t

> 
```

Note that when [searching for the type `a -> a`](https://pursuit.purescript.org/search?q=a+-%3E+a) in Pursuit, only the `Neon.Primitive.Function.identity` function was found, which seems to be what I was looking for.

**Comment by ptrfrncsmrph** [comment]
```haskell
forall a. a -> a
```
is a specialized version of [`Prelude.identity`](https://pursuit.purescript.org/packages/purescript-prelude/6.0.1/docs/Control.Category#v:identity)
```haskell
identity :: forall a t. Category a => a t t
```
where `Category a` is fixed to the function arrow `(->)`
```haskell
identity :: forall t. (->) t t
-- or with the -> infix
identity :: forall t. t -> t
```
but I agree that that's not beginner-friendly output to see for `:t identity` in the REPL 😞

**Comment by JordanMartinez** [comment]
`id` was renamed to `identity` at some point. So this part of the book should be updated to reflect that.

**Comment by gemmaro** [comment]
Thank you for telling me. I am strolling `Control.Category` and Haskell's `Control.Arrow`.

I am thinking about the following revision.
(If it's better to have a paragraph and deep explanation, I'd appreciate it if someone who knows the details could write it, since I don't write English very well.)

````diff
diff --git a/text/chapter10.md b/text/chapter10.md
index 7348381..5145414 100644
--- a/text/chapter10.md
+++ b/text/chapter10.md
@@ -1253,11 +1253,11 @@ Consider this polymorphic type, for example:
 forall a. a -> a
 ```
 
-What sort of functions have this type? Well, there is certainly one function with this type - namely, the `identity` function, defined in the `Prelude`:
+What sort of functions have this type? Well, there is certainly one function with this type - namely, [the `identity` function](https://pursuit.purescript.org/packages/purescript-prelude/docs/Control.Category#v:identity), defined in the `Prelude` (Strictly speaking, the signature is more specific than the actual one.):
 
 ```haskell
-id :: forall a. a -> a
-id a = a
+identity :: forall a. a -> a
+identity a = a
 ```
 
 In fact, the `identity` function is the _only_ (total) function with this type! This certainly seems to be the case (try writing an expression with this type which is not observably equivalent to `identity`), but how can we be sure? We can be sure by considering the runtime representation of the type.
````

**Comment by JordanMartinez** [comment]
Here's my explanation for `Category` and `Semigroupoid`: https://jordanmartinez.github.io/purescript-jordans-reference-site/content/21-Hello-World/01-Prelude-ish/05-Composition-Typeclasses/06-Arrows--Semigroupoid-and-Category.html?highlight=semigroupoid#generalizing-to-more-types
