### ISSUE TITLE
Chapter 8 uses affjax, but it's not a package set. Make a PR to add it to the package sets

### ISSUE THREAD

**Issue by dwhitney** [purescript-contrib/purescript-book#43]

**Comment by FranklinChen** [comment]
Note: affjax 10.0.0 has been released https://github.com/slamdata/purescript-affjax/releases/tag/v10.0.0

**Comment by dwhitney** [comment]
Cool. I'm out of town with limited internet until next week

**Comment by emiel** [comment]
So `affjax` was added back in to purescript/package-sets in https://github.com/purescript/package-sets/commit/fd4dde95dfc26f3761833ece15592e0f9ab7e728. As far as I can tell the chapter 8 exercise now compiles using spago. Can this issue be closed?
