### ISSUE TITLE
Swap of Ch4 and Ch5 incomplete

### ISSUE THREAD

**Issue by d-s-d** [purescript-contrib/purescript-book#462]
There is a note in Ch5 that now refers to pattern matching being introduced in [«[...] in a later chapter [...]»](https://github.com/purescript-contrib/purescript-book/blob/874eefeb4b9c6635bec5021ef59fdf8d0038978b/text/chapter5.md?plain=1#L49)—however, it is now introduced in Ch4. Also, the code examples would need to be updated accordingly; i.e. use pattern matching instead of if/else.

Stupid question: what is the best way to contribute here?

**Comment by Zelenya** [comment]
Oh, my bad, thank you for catching these. Opening Pull Request with changes would be very helpful, see [the Contribution guide](https://github.com/purescript-contrib/purescript-book/blob/master/CONTRIBUTING.md) for instructions
