### ISSUE TITLE
Can you clarify this no peeking stuff?

### ISSUE THREAD

**Issue by nyck33** [purescript-contrib/purescript-book#467]
oh, that's not quite right. Let's fix this with the correct application of the Pythagorean formula by changing the function to:

```hs
{{#include ../exercises/chapter2/test/no-peeking/Solutions.purs:diagonal}}
```
so you want me to paste that into MySolutions.purs because that does not work

```
(base) nyck33@lenovo-15ACH6:~/ps/purescript-book/exercises/chapter2$ spago test
Error found:
at test/MySolutions.purs:9:1 - 9:2 (line 9, column 1 - line 9, column 2)

  Unable to parse module:
  Unexpected token '{'


See https://github.com/purescript/documentation/blob/master/errors/ErrorParsingModule.md for more information,
or to contribute content related to this error.
```
Copilot is saying that's not valid purescript so it'll throw the error.  
Can you edit documentation to go a bit more step by step maybe show the entire file with that pasted in, etc because it's a bit opaque at the moment.  

[error] Failed to build.
(base) nyck33@lenovo-15ACH6:~/ps/purescript-book/exercis

**Comment by pete-murphy** [comment]
Hey :wave: where are you reading the book? When I go to https://book.purescript.org/chapter2.html I see 
<img width="811" alt="image" src="https://github.com/purescript-contrib/purescript-book/assets/26548438/6e7cb109-ec44-4c77-a601-1706dd4c4e17">

> Uh-oh, that's not quite right. Let's fix this with the correct application of the Pythagorean formula by changing the function to:
>
> ```purs
> diagonal w h = sqrt (w * w + h * h)
> ```

**Comment by nyck33** [comment]
![image](https://github.com/purescript-contrib/purescript-book/assets/25189545/80df1e53-2981-453e-9f27-d383c940b9b2)

I"m reading it in VS Code on Ubuntu 23.
