### ISSUE TITLE
Render book to single file

### ISSUE THREAD

**Issue by flip111** [purescript-contrib/purescript-book#48]
Would be nice to be able to render to book into a single file (like pdf). I know i can use pandoc, but i think it could use a little more like a Contents section.

**Comment by flip111** [comment]
```bash
pandoc -t html -s -o purescript.pdf $(ls text/*.md | sort -V)
```

**Comment by milesfrain** [comment]
I'm hoping we could render the final output somewhat like the [original book](https://leanpub.com/purescript/read), where you have everything searchable on a single page, along with a collapseible table of contents.

**Comment by flip111** [comment]
Maybe a static html generator in that case so it can be used online and offline. I don't what generators are out there. Maybe a static html documentation generator would do.

https://docsify.js.org/#/

**Comment by s0kil** [comment]
What about enabling GitHub pages for the repo? Here is an [example](https://s0kil.github.io/purescript-book/text/chapter1.html) and the [config](https://github.com/s0kil/purescript-book/blob/master/_config.yml) that enables is.

**Comment by milesfrain** [comment]
@s0kil I'm all for easy steps that improve the current situation, and so I'd be happy to start with a github pages version for now while we continue our investigation into the available options.
If you make the PR, I'll merge it.

Some missing features from the original book that I'd like to eventually see are:
* Render entire book on a single web page, this makes searching a lot easier
* Show contents on side bar
* Allow linking to sections within chapters
* Render exercise heading. Not sure why `##` is supported in regular `.md` markdown but not in the webpage output.

**Comment by s0kil** [comment]
@milesfrain To add the functionality that you have mentioned, we could rather start off using Gitbook.

**Comment by milesfrain** [comment]
GitBook looks promising.
Here's an [example](https://cesarvandevelde.gitbooks.io/herkulexservo/tutorial.html).

Some questions / concerns are:
* Do we need to update the [`SUMMARY.md`](https://github.com/cesarvandevelde/HerkulexServo/blob/master/docs/SUMMARY.md) when chapter sections change. That might become annoying.
* Still can't view entire book as a single page
* Not clear how to download book as PDF

**Comment by s0kil** [comment]
Here is what it turns out like https://daniel-sokil.gitbook.io/purescript-book/
Also PDF export requires a paid subscription, maybe free for open-source?.
What is the reasoning behind single page layout? The search indexes through all pages.

**Comment by milesfrain** [comment]
Nice work! I think GitBook gets us most of the way there, but there are still some annoyances:

* Pages load kinda slow. Takes about a second for the loading bar at the top of the screen to complete. I'd expect this to be instant for cached static pages. I wonder if this is punishment for free tier users.
* Their search feature is not as good as simple browser-based search. For example searching for `kind` gives me all sorts of stuff that isn't `kind`. Adding quotes doesn't help either.
![image](https://user-images.githubusercontent.com/3578681/79079584-4b331400-7ccd-11ea-9333-502c520f7d71.png)

**Comment by milesfrain** [comment]
Some other GitBook concerns:
* It's more strict than markdown about escaping parenthesis and other symbols. [Example](https://github.com/s0kil/purescript-book/commit/a67c328be21dd74ae182555000ea6b31a6286f1d#diff-22c9ff9a154bed6a81aef9ac3e8a3eaaR145).
* It doesn't like numbered list shorthand of just repeating `1.`. [Example](https://github.com/s0kil/purescript-book/commit/a67c328be21dd74ae182555000ea6b31a6286f1d#diff-0fe453717bf45cb929f3a70bc84bacf5L390).

**Comment by JordanMartinez** [comment]
What about [pandoc](https://pandoc.org/)?

**Comment by milesfrain** [comment]
I was wondering how the [Rust Book](https://doc.rust-lang.org/stable/book/) configures their GitBook instance to enable [one-page-view](https://doc.rust-lang.org/stable/book/print.html) and printing.
Turns out they made their own GitBook clone. I propose we explore using [mdBook](https://github.com/rust-lang/mdBook), and we can use the [rust-book repo](https://github.com/rust-lang/book) as a guideline on how to setup this repo along with the necessary Travis-CI job to keep it up to date.

**Comment by milesfrain** [comment]
> What about [pandoc](https://pandoc.org/)?

@JordanMartinez Could you point us to an example project that uses pandoc?

**Comment by JordanMartinez** [comment]
Meaning, pandoc could be used to create a single downloadable PDF file of this entire repo. I'm guessing you could set up a Travis CI deploy hook to run such a program when you make a release build?
Unfortunately, I don't know of a project that uses it already.

**Comment by s0kil** [comment]
What about sticking to something as simple as https://s0kil.github.io/purescript-book/book/ ?
- Sure we could add content navigation.
- Take advantage of browser search and export to PDF using `print -> save as PDF`.

**Comment by milesfrain** [comment]
> What about sticking to something as simple as https://s0kil.github.io/purescript-book/book/ ?
That seems to tackle most of the requirements, and I'd be happy to go with that for now.

I'm probably going to also investigate the `mdbook` option in the next day or so unless someone else wants to take-on that effort.

**Comment by s0kil** [comment]
Should I open a PR?

**Comment by milesfrain** [comment]
> Should I open a PR?

PR looks good. Will wait a few hours for others to provide feedback before merging.

**Comment by JordanMartinez** [comment]
What else needs to be done before this issue can be closed? Are there any other chapters in the Readme that we should explicitly mention are still being updated?

**Comment by milesfrain** [comment]
To leave no stone unturned, I gave [mdbook](https://github.com/rust-lang/mdBook) a try with a [minimal config](https://github.com/milesfrain/purescript-book/commit/2134f05918e994c18b16eb02944771068bd00577).

Here's the output:
https://milesfrain.github.io/purescript-book/

I like that TOC appears in a collapsible sidebar, although more work is needed to display all section headings.

Another cool feature is that we can [link code snippets in the text directly to `.purs` files](https://rust-lang.github.io/mdBook/format/mdbook.html#including-portions-of-a-file) so the book stays in sync with the code.

It also has a [single-page view](https://milesfrain.github.io/purescript-book/print.html) and handles duplicate anchors gracefully. The current sequential anchoring approach from #80 will break old links if any previous sections are added or removed.
For example if: https://book.purescript.org/#108-Superclasses becomes https://book.purescript.org/#107-Superclasses
Fixing this is straightforward in our custom solution, but I'm wondering if it's wiser to take advantage of the work already put into developing mdbook, rather than reinvent a custom alternative.

**Comment by s0kil** [comment]
I also would prefer going with mdbook, it seems to be a better option for long term.
Also, you previously wanted to view entire book as a single page, what about now?
Is it possible to style mdbook? What about PDF export?

**Comment by JordanMartinez** [comment]
Yeah, that does come with a few features that the current approach does not have:
- a dark theme
- a search bar
- each chapter exists as its own page, so one can easily navigate throughout the page via the left/right arrow keys without feeling overwhelmed with the entire book displayed in one page.
- potentially, a way to run PureScript code...?

**Comment by JordanMartinez** [comment]
> Is it possible to style mdbook?

Seems like it. See https://rust-lang.github.io/mdBook/format/config.html#html-renderer-options

**Comment by s0kil** [comment]
If we continue with mdbook and a custom theme, that would be good.
Let's not make it end up looking generic as most mdbook pages.

**Comment by emiel** [comment]
+1 for mdbook

**Comment by milesfrain** [comment]
> Also, you previously wanted to view entire book as a single page, what about now? What about PDF export?

Yep, see the [single-page view](https://milesfrain.github.io/purescript-book/print.html) link in the previous post (also opens-up print-to-pdf dialog).

I believe #82 is the next step to move forward with mdbook. Might be part of what #34 had in-mind too.

**Comment by JordanMartinez** [comment]
Nice!

**Comment by s0kil** [comment]
Now that @milesfrain has made good progress with mdbooks and #82 has been merged, it's a good time to close this issue.

**Comment by s0kil** [comment]
Sometimes using the mdbooks print page could cause system to run out of memory, so here is a friendlier way:
`chrome --headless --print-to-pdf=PureScript-Book.pdf https://book.purescript.org/print.htm`

**Comment by milesfrain** [comment]
Wondering if that printing note should be added to the main readme.

Feel free to file additional tasks for the other todos, such as adding a custom theme, like we had in with @s0kil's version.

Closing this issue
