### ISSUE TITLE
Example in Chapter 4 has warnings

### ISSUE THREAD

**Issue by kevinbarabash** [purescript-contrib/purescript-book#50]
In the follow example:
```
length' :: forall a. Array a -> Int
length' arr = length arr 0
  where
    length :: forall a. Array a -> Int -> Int
    length arr acc =
      if null arr
        then 0
        else length (fromMaybe [] $ tail arr) acc + 1
```
The two variables `a` and `arr` in `length` shadow declarations from `length'`.  It might be good to call this out in the text.

**Comment by milesfrain** [comment]
Good catch!
I think it's best to just eliminate the shadowing issue. #54 is one way to do that. Still tough to decide on the best names for everything.

**Comment by milesfrain** [comment]
We may close this issue now that #54 is merged.
