### ISSUE TITLE
Remove `purescript-` prefixes from packages

### ISSUE THREAD

**Issue by milesfrain** [purescript-contrib/purescript-book#66]
As discussed in #61, these package prefixes are unnecessary (and warned against) when installing via spago.

What are maintainers thoughts on stripping out all `purescript-` prefixes from packages mentioned in the book text?

I think all packages can be assumed to be part of the purescript ecosystem unless otherwise specified (eg, "`request` module via NPM" in ch12).

**Comment by hdgarrood** [comment]
The prefixes are an artifact of using the Bower registry. They're on the way out, eg https://github.com/purescript/registry/pull/4

**Comment by milesfrain** [comment]
Merged in #70
