### ISSUE TITLE
A few comments on issues with Chapter 1

### ISSUE THREAD

**Issue by JordanMartinez** [purescript-contrib/purescript-book#69]
After reading through it, here's a few issues that come to mind:
- What is the purpose of the book and who is it for? The [LeanPub summary](https://leanpub.com/purescript) isn't mentioned anywhere here.
- Why should one use PureScript? At the very least, there might be links to other articles that cover that, like the one written by Phil himself.
- Why is my learning reference not mentioned in the 'getting started' guide? If this was the first learning resource one came across, they would have to go to the documentation repo and find my resource in a section on the ReadMe.
- Is the PureScript IRC channel still a valid communication line? I thought Slack was the main one for that now.
- Try PureScript is likewise outdated and should probably be unlinked until after core contributors finish updating it to the 0.13 release. We should also include a note about this resource's outdatedness to forewarn people.

**Comment by hdgarrood** [comment]
> What is the purpose of the book and who is it for?

Copying the "About the book" text from leanpub into the project readme is probably a good idea, yes. I think the "who is it for" is pretty well covered by the "About you" section in chapter 1: https://github.com/purescript-contrib/purescript-book/blob/master/text/chapter1.md#about-you

> Why should one use PureScript?

I think this is already covered too? From the beginning of the chapter:

> PureScript is a programming language which aims to address these issues. It features lightweight syntax, which allows us to write very expressive code [...]

> Why is my learning reference not mentioned in the 'getting started' guide?

The book predates your reference by a few years, I think. Adding a link to your reference in the "Getting help" section sounds good to me.

> Is the PureScript IRC channel still a valid communication line? I thought Slack was the main one for that now.

I think recommending Slack over IRC makes sense, yes. I think IRC is still in use but I don't think it's as popular as Slack is.

> Try PureScript is likewise outdated and should probably be unlinked until after core contributors finish updating it to the 0.13 release. We should also include a note about this resource's outdatedness to forewarn people.

This sounds fine but please do remember to add the link back when it is updated. I am working on this right now and we are very close to deploying an updated version.

**Comment by JordanMartinez** [comment]
>> Why should one use PureScript?
>
> I think this is already covered too? From the beginning of the chapter:

I kind of had [Why you should use purescript](https://gist.github.com/paf31/adfd15fbb1ac8b99fc68be2c9aca8427) in mind...

> The book predates your reference by a few years, I think. Adding a link to your reference in the "Getting help" section sounds good to me.

I guess I was surprised that others who had been updating this book hadn't linked to my resource.

>> Try PureScript is likewise outdated and should probably be unlinked until after core contributors finish updating it to the 0.13 release. We should also include a note about this resource's outdatedness to forewarn people.
>
> This sounds fine but please do remember to add the link back when it is updated. I am working on this right now and we are very close to deploying an updated version.

I decided not to remove it. Rather, I just included a note that we don't advise using it until its updated and that it's produce `v0.11.x` PureScript code.

**Comment by milesfrain** [comment]
Added some PR feedback to #72 

> I guess I was surprised that others who had been updating this book hadn't linked to my resource.

I think the common discovery process of PS documentation from page links is:
* purescript.org
  * Documentation Repo
    * Purescript Book
    * Jordan's Reference

So it seems that most learners would be aware that your reference exists. It doesn't hurt to cross-link though.

Chapter 1 is also the most skimmable, and fixing the more severely broken content of the remaining chapters took priority.

**Comment by JordanMartinez** [comment]
> So it seems that most learners would be aware that your reference exists. It doesn't hurt to cross-link though.

Cross-linking is good. It decreases the chance that they'll miss it. I do remember someone not knowing about my repo, but I can't remember where that was mentioned.

> Chapter 1 is also the most skimmable, and fixing the more severely broken content of the remaining chapters took priority.

That makes sense. Upon reflection, I was working on my repo during the same time that dwhitney was updating the book.
