### ISSUE TITLE
Exercises/Conclusion header names clash in Livebook

### ISSUE THREAD

**Issue by JordanMartinez** [purescript-contrib/purescript-book#76]
See #73 and #75 for more context.

If you click on the ToC's 'Exercises' header links to a chapter other than the second one, it'll redirect to the second chapter's Exercises section, not the corresponding section of that chapter. This is due to the headers using the same text.

**Comment by s0kil** [comment]
I'm thinking to prefix each chapter to section name in each link.
So, `Exercises` turns into `Getting Started Exercises`

**Comment by JordanMartinez** [comment]
Sounds good. I'll update that PR.

**Comment by JordanMartinez** [comment]
Hm... only issue with that is that some chapters have multiple Exercise sections. I'm not very familiar with this book, so it would probably be better to have someone else provide unique header names. Otherwise, I'll be reading through the entire book before I could do that.

**Comment by JordanMartinez** [comment]
I'm reposting @hdgarrood's comment from my previous PR in this issue so that it doesn't get lost:

> This way we are effectively saying that we need to ensure that headings are unique throughout the repo, which I think is going to be difficult to do. What if we changed the JS in index.html to include the chapter number in the generated HTML id attributes?

**Comment by s0kil** [comment]
We could turn -> "Exercises" -> "Getting Started Exercises" + uniqueID

**Comment by JordanMartinez** [comment]
In case others have already viewed the page before this change occurred, you will need to force-reload the page via Shift+F5 to experience the new behavior. 

Thanks for your work @s0kil!
