### ISSUE TITLE
Ch 5: Cannot identify any realistic use for array literal pattern for exercise 'fromSingleton'

### ISSUE THREAD

**Issue by oldfartdeveloper** [purescript-contrib/purescript-book#83]
Here's the exercise statement:

> (Medium) Write a function `fromSingleton` which uses an array literal pattern to extract the sole member of a singleton array. If the array is not a singleton, your function should return a provided default value. Your function should have type `forall a. a -> Array a -> a`

I don't think there's any scenario in which the array literal pattern makes sense.  Here are 3 different implementations I explored:

```haskell
fromSingleton :: ∀ a. a -> Array a -> a
fromSingleton def arr = case uncons arr of
  Just { head: x, tail: xs } -> if 0 == length xs then x else def
  Nothing -> def

fromSingleton' :: ∀ a. a -> Array a -> a
fromSingleton' def arr
  | 1 == length arr = fromMaybe def $ head arr
  | otherwise = def

fromSingleton'' :: ∀ a. a -> Array a -> a
fromSingleton'' def [] = def
fromSingleton'' _ [ x ] = x
fromSingleton'' def _ = def
```

The exercise's clue recommends using the array literal pattern for the sole member of the singleton array.  The problem I see is that the sole member never changes to another value, and so there's no need to use an array literal pattern to cache it.

If I'm correct, then this exercise does not successfully demonstrate the array literal pattern and should be deleted or changed.

I welcome "the answer" that I haven't thought of yet.  Any takers?

**Comment by hdgarrood** [comment]
Your third option is closest to what I think the exercise has in mind:
```purescript
fromSingleton :: forall a. a -> Array a -> a
fromSingleton _ [x] = x
fromSingleton def _ = def
```
The `[x]` in the first case is what is meant by an array literal pattern for the singleton array. (Incidentally the first pattern in your `fromSingleton''` is not necessary, since passing an empty array as the second argument will fall through to the `def _ = def` case anyway.)

**Comment by hdgarrood** [comment]
> The problem I see is that the sole member never changes to another value, and so there's no need to use an array literal pattern to cache it.

I don't see what you're getting at here; patterns don't really "cache" things in any way that I can see, and all arrays are immutable anyway, regardless of how you match on them. Can you elaborate on this? What did you think was meant by an array literal pattern?

**Comment by oldfartdeveloper** [comment]
@hdgarrood Ahh, I conflated the definition of "array literal pattern", defined at the beginning of the section, with "named pattern" which appeared just before the exercise. Now that I see it, it's obvious that I mistakenly tried to apply "named pattern".  My bad.  Thanks for the correction.

In looking more closely, all titles in the page are at the same level (all use markdown `##`), so I need to remember that information needed for an exercise can go back to the previous group of exercises.

Or, would it be helpful if an exercise requires using a concept, to place the question within the concept's section?  It serves no purpose placing below a different concept's conception, and makes it more probable that a reader is derailed as I was.

Heck, I'll make the change and submit as a PR.

**Comment by milesfrain** [comment]
> 'll make the change and submit as PR #84. Let me know what you think.

This type of reorganization would affect the entire book. Shared some of my thoughts about it in the PR.

**Comment by milesfrain** [comment]
Closing this issue now that #84 is open
