### ISSUE TITLE
Update Chapter 3 AddressBook.purs

### ISSUE THREAD

**Issue by p2327** [purescript-contrib/purescript-book#87]
Ignore

**Comment by milesfrain** [comment]
I think your original point of confusion is still valid. It would be better to leave your original post and maybe add an edit describing the solution you found in case other readers in the future have the same experience.

I've also been confused by mismatches of early code snippets in the text that don't match the final form in the .purs file. Open to ideas of how to improve this.

Closing this issue, but will keep an eye out if other readers report similar problems.
