### ISSUE TITLE
Ch2 consolidate getting-started guides

### ISSUE THREAD

**Issue by milesfrain** [purescript-contrib/purescript-book#93]
There's a lot of duplicated information between this guide:
https://github.com/purescript/documentation/blob/master/guides/Getting-Started.md
and the getting-started chapter:
https://book.purescript.org/chapter2.html

It would be great if we could combine both of these into chapter 2, then [purescript.org](https://www.purescript.org/) could link directly to ch2 of the book, instead of the first guide.

**Comment by hdgarrood** [comment]
My preference would be to keep the one in the documentation repo and link to it from here, because it has the “next steps” at the bottom which ought to be useful for most people who have just installed purescript, whether or not they are new to FP, and whether or not they are working through this book.

**Comment by hdgarrood** [comment]
I suppose a downside of that is that the book is no longer self-contained: if someone downloads the book in preparation for use on a flight or something, it’s going to be a bit of a letdown if the getting started instructions are elsewhere on the internet. I think this is why it’s perhaps not such a bad thing to have two different copies of it (not that we shouldn’t try to consolidate them, though).

**Comment by milesfrain** [comment]
> keep the one in the documentation repo and link to it from [the book]
Would that mean the contents of Ch2 would just be a note and a link?

> I think this is why it’s perhaps not such a bad thing to have two different copies
My concern with two copies is that they'll inevitably diverge, increase maintenance efforts, and be annoying for newcomers.

What is the downside of absorbing the docs repo version into the book? We could include a "Next Steps" section at the end of the chapter to either let users continue on with reading the book or explore another path. I think that would be the cleanest solution.

**Comment by hdgarrood** [comment]
Perhaps, although in that case there's not much point in dedicating a whole chapter to just a note and a link; if we were just going to provide a link, then it would probably make more sense to remove the "Getting started" chapter and instead provide links at the end of the introduction and at the start of what is currently chapter 3. My hesitation about having this repo be the canonical place for it is that I don't think the getting started guide should be tied to any particular learning resource, and I also think that it should be in the `purescript` org, and the core team should be approving any changes to it.

**Comment by milesfrain** [comment]
That works. Maybe we could replace chapter 2 with a discussion on how tests for exercises work.
